version: '3'

services:
  api:
    image: ananaso/cephs-unitconverter-api
    depends_on:
      - 'database'
    ports:
      - '3333:3333'
    restart: unless-stopped

  unitconverter:
    image: ananaso/cephs-unitconverter-app
    depends_on:
      - 'api'
    ports:
      - '3000:3000'

  database:
    image: fallensteed/cephs-db
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment: 
      POSTGRES_PASSWORD: ceph
      POSTGRES_USER: ceph
      POSTGRES_DB: cephs_citchen